### ISSUE TITLE
重构后的Bug和优化记录

### ISSUE THREAD

**Issue by Aoi-hosizora** [Aoi-hosizora/Biji_Baibuti#23]
+ 全局
    + ~~**结巴分词初始化 GC OOM**~~
    + OnResume 待整理
    + ~~ActionBar Overlap~~
    + ~~添加 Launch Activity~~
    + ~~添加 About Activity~~
+ 认证
    + ~~登录注册的按钮没有对齐~~
    + ~~还没存储登录 Token~~
+ 笔记
    + ~~分组对话框无法输入~~
    + ~~默认分组删除重复~~
    + ~~删除分组后分组列表没有更新导致崩溃~~
    + ~~笔记分组顺序调整无效~~
    + ~~**分组和搜索后修改笔记无效**~~
    + ~~**插入笔记图片后rx无法跳转到编辑界面**~~
    + ~~Fab 蒙版延时问题~~
    + ~~搜索和分组添加 ProgressDlg~~
+ 搜索
    + 百度搜索结果的链接没有转换
    + 加载更多经常找不到内容
    + ~~**收藏的搜索出错**~~
+ 课表
    + ~~**当前周没有记录**~~
    + ~~**课表查询登录后没有跳转**~~
    + 点击单元格的加号隐藏
    + 教师信息显示
    + **课表信息经常无法解析**
+ 资料
    + ~~导入文件的Adapter没有setOnClick在view上~~
    + 导入文件对话框允许从文件夹选择，和打开保存文件合并
    + ~~**按照分组共享和按照文件共享**~~
    + ~~**打开文档错误**~~
    + ~~文档弹出菜单崩溃~~
    + ~~**搜索框未修改**~~
    + 分组信息的顺序
    + ~~选择别的分组可以弹出ProgressDlg~~
    + ~~**文件上传和下载，显示进度**~~
    + ~~**删除分组并移动默认分组崩溃**~~
    + ~~**删除分组后没更新**~~
    + **重复添加文档**
    + ~~**转移分组未写**~~
    + ~~刷新文档列表跳转到分组~~
    + 无法下拉 EmptyView
    + ~~文档文件名上传后被SecureCheck被修改~~
    + ~~**下载的搜索未写**~~
    + ~~**action_all_share_documents 未实现**~~

**Comment by Aoi-hosizora** [comment]
+ 记录：
```java
// openFile
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
    StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
    StrictMode.setVmPolicy(builder.build());
}
```

**Comment by Aoi-hosizora** [comment]
+ 临时记录：
```
error_exception:  unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "E:\Program Files (x86)\Python\Python36\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Program Files (x86)\Python\Python36\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "F:\プログラム\Biji_BackEnd\app\controller\AuthCtrl.py", line 47, in LoginRoute
    token = AuthUtil.generate_token(user.id, ex)
  File "F:\プログラム\Biji_BackEnd\app\util\AuthUtil.py", line 25, in generate_token
    'uid': uid
  File "E:\Program Files (x86)\Python\Python36\lib\site-packages\itsdangerous.py", line 740, in dumps
    header = self.make_header(header_fields)
  File "E:\Program Files (x86)\Python\Python36\lib\site-packages\itsdangerous.py", line 788, in make_header
    exp = iat + self.expires_in
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by Aoi-hosizora** [comment]
+ GC OOM 记录：
通过指定 largeHeap 才防止了 OOM
```xml
 <application
        android:name=".MyApplication"
        android:allowBackup="true"
        android:largeHeap="true" />
```

**Comment by Aoi-hosizora** [comment]
+ 本地的文档：
    + 扫描：加入不重复文件的全路径名
    + 打开：直接根据路径打开文件
    + 分享：不支持
    + 获取分享：支持，根据 sc 下载后添加到本地下载记录 SP
+ 登陆的文档：
    + 扫描：上传文件，加入不重复文件的文件名
    + 打开：根据 did 下载文件到本地，加入到本地下载文件记录 SP
    + 分享：按照分组 cid 或者文档 did[] 生成分享码
    + 获取分享：支持，根据 sc 下载后添加到本地下载记录 SP
